CREATE TABLE [dbo].[InvestmentAccount](
	[Id] [UNIQUEIDENTIFIER] NOT NULL,
	[UserId] [UNIQUEIDENTIFIER] NOT NULL,
	[Name] [NVARCHAR](100) NOT NULL,
	[Type] [SMALLINT] NOT NULL,
	[CurrentAmount] [FLOAT] NULL
 CONSTRAINT [PK_InvestmentAccount] PRIMARY KEY CLUSTERED
 (
	[Id] ASC
 )
 WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Investment](
	[Id] [UNIQUEIDENTIFIER] NOT NULL,
	[InvestmentAccountId] [UNIQUEIDENTIFIER] NOT NULL,
	[Name] [NVARCHAR](100) NOT NULL,
 CONSTRAINT [PK_Investment] PRIMARY KEY CLUSTERED
 (
	[Id] ASC
 )
 WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[Investment] ADD CONSTRAINT FK_Investment_InvestmentAccountId FOREIGN KEY (InvestmentAccountId) REFERENCES [dbo].[InvestmentAccount](Id);
GO

CREATE TABLE [dbo].[InvestmentValue](
	[Id] [UNIQUEIDENTIFIER] NOT NULL,
	[InvestmentId] [UNIQUEIDENTIFIER] NOT NULL,
	[Date] [DATE] NOT NULL,
	[Value] [FLOAT] NOT NULL,
 CONSTRAINT [PK_InvestmentValue] PRIMARY KEY CLUSTERED
 (
	[Id] ASC
 )
 WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[InvestmentValue] ADD CONSTRAINT FK_InvestmentValue_InvestmentId FOREIGN KEY (InvestmentId) REFERENCES [dbo].[Investment](Id);
GO
