CREATE TABLE [dbo].[MonthlyValue](
	[Id] [UNIQUEIDENTIFIER] NOT NULL,
	[AccountId] [UNIQUEIDENTIFIER] NOT NULL,
	[Date] [DATE] NOT NULL,
	[Value] [FLOAT] NOT NULL
 CONSTRAINT [PK_MonthlyValues] PRIMARY KEY CLUSTERED
 (
	[Id] ASC
 )
 WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[YearlyValue](
	[Id] [UNIQUEIDENTIFIER] NOT NULL,
	[AccountId] [UNIQUEIDENTIFIER] NOT NULL,
	[Year] [INT] NOT NULL,
	[Value] [FLOAT] NOT NULL
 CONSTRAINT [PK_YearlyValues] PRIMARY KEY CLUSTERED
 (
	[Id] ASC
 )
 WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
